pictures: signal_shape.png               \
          example_signal.png             \
          likelihood_and_posterior.png   \
          posterior_final.png            \
          likelihood_and_posterior_no_signal.png   \
          posterior_final_no_signal.png            \
          leading_half.png               \


%.png: %.gp
	gnuplot $+

clean:
	rm *.png 