pictures: signal_shape.png               \
          example_signal.png             \
          likelihood_and_posterior.png   \
          posterior_final.png            \
          leading_half.png               \
          

%.png: %.gp
	gnuplot $+

clean:
	rm *.png 